services:
  api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: task_manager_app
    env_file:
      - ./backend-api/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend-api:/app
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: task_manager_db
    env_file:
      - ./backend-api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend-api/docker/initdb:/docker-entrypoint-initdb.d
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile
    container_name: task_manager_frontend
    ports:
      - "3000:3000"
    environment:
      - API_INTERNAL_URL=http://api:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend-nextjs:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
