"""updated table name

Revision ID: 35a4906fa048
Revises: ba78c626b892
Create Date: 2025-09-16 21:06:00.667682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a4906fa048'
down_revision: Union[str, Sequence[str], None] = 'ba78c626b892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_hashed_token'), 'password_resets', ['hashed_token'], unique=True)
    op.drop_index(op.f('ix_password_reset_requests_hashed_token'), table_name='password_reset_requests')
    op.drop_table('password_reset_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hashed_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_requests_pkey'))
    )
    op.create_index(op.f('ix_password_reset_requests_hashed_token'), 'password_reset_requests', ['hashed_token'], unique=True)
    op.drop_index(op.f('ix_password_resets_hashed_token'), table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
